runtime: nodejs18 # or another supported version

#instance_class: F2
#env: legacy

#manual_scaling:
#instances: 1

#resources:
#cpu: 1
#memory_gb: 0-5
#disk_size_gb: 10

#env_variables:
#  BUCKET_NAME: "code-bucket"

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png|jpg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|jpg)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  REACT_APP_SERVICE_ID: "service_5uovyug"
  REACT_APP_TEMPLATE_ID: "template_jq5khja"
  REACT_APP_USER_ID: "ZM5XigbNzoPx1fNY3"
  GENERATE_SOURCEMAP: false
